float32 x_setpoint
float32 x_measurement
float32 x_power

float32 y_setpoint
float32 y_measurement
float32 y_power

float32 z_setpoint
float32 z_measurement
float32 z_power

float32 roll_setpoint
float32 roll_measurement
float32 roll_power

float32 pitch_setpoint
float32 pitch_measurement
float32 pitch_power

float32 yaw_setpoint
float32 yaw_measurement
float32 yaw_power

bool x_mode
bool y_mode
bool z_mode
bool roll_mode
bool pitch_mode
bool yaw_mode